apiVersion: v1
kind: Service
metadata:
  name: lb-k8s
  namespace: envoy-gateway-system
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: LoadBalancer # Type du service
  selector:
    app: envoy-gateway # Correspond aux pods ayant le label "app: my-app"
  ports:
    - protocol: TCP
      port: 80 # Port externe exposé par le load balancer
      targetPort: 80 # Port cible des pods
      name: http
    - protocol: TCP
      port: 443 # Port externe exposé par le load balancer
      targetPort: 443 # Port cible des pods
      name: https
  externalTrafficPolicy: Cluster # Optionnel : définit la politique de routage du trafic externe