service:
  enabled: true
  type: ClusterIP

plugins:
  - https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v0.10.1/victoriametrics-datasource-v0.10.1.zip;victoriametrics-datasource

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server.monitoring.svc.cluster.local
     access: proxy
     isDefault: true
  #  - name: VictoriaMetrics
  #    type: victoriametrics-datasource
  #    access: proxy
  #    url: http://vm-rel-victoria-metrics-single-server.vm-ns.svc.cluster.local:8428
  #    isDefault: false
  #    jsonData:
  #     prometheusType: Prometheus
  #     prometheusVersion: 2.24.0

grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ tpl (.Values.ingress.hosts | first) . }}{{ else }}''{{ end }}"
  plugins:
    allow_loading_unsigned_plugins: "victoriametrics-datasource"

imageRenderer:
  env:
    HTTP_HOST: "0.0.0.0"
    GF_INSTALL_PLUGINS: "https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v0.10.1/victoriametrics-datasource-v0.10.1.zip;victoriametrics-datasource"
    GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "victoriametrics-datasource"