---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gat-eg
  annotations:
      # external-dns.alpha.kubernetes.io/hostname: testgateway.testgateway.bastienbyra.fr
      # external-dns.alpha.kubernetes.io/ttl: "120"
      # external-dns.alpha.kubernetes.io/endpoints-type: "107.155.122.60"
      cert-manager.io/cluster-issuer: "letsencrypt-gateway-production"
spec:
  gatewayClassName: eg
  addresses:
  - type: IPAddress
    value: 107.155.122.60
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      hostname: testgateway.bastienbyra.fr
      tls:
        certificateRefs:
        - kind: Secret
          group: ""
          name: testgatewayaaa-com-cert
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    service: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      serviceAccountName: backend
      containers:
        - image: 8271/bbyra-website:8053d6556c4a43395ba304fd31bfa3116d0362c6
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: gat-eg
  hostnames:
    - "testgateway.bastienbyra.fr"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: backend
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
